### ISSUE TITLE
Is the labeled structure ACTN1 or ACTN2?

### ISSUE THREAD

**Issue by danrlu** [AllenCell/cvapipe_analysis#70]
Hi, thanks so much for this very useful workflow to interact with AllenCell data! 

I must be missing something. In the Structures section in README.md
<img width="828" alt="image" src="https://github.com/user-attachments/assets/9ce39f4d-1168-405e-8c57-30b0c1db654f">
as well as the `manifest.csv` in the download, it's all `ACTN1`. 

But on AllenCell catelog https://www.allencell.org/cell-catalog.html there is only `ACTN2`. 
Which one is actually labeled in the imaging data? 

Thanks!

**Comment by vianamp** [comment]
Hi. We used ACTN1 and not ACTN2 in the Nature manuscript. However, we haven't release the ACTN1 line though yet due to some technical difficulties. If you have further questions about the cell lines I encourage you to post them in our Forum (https://forum.allencell.org/) where it is visible to more people.

**Comment by danrlu** [comment]
Thanks for the clarification!
